<a href="https://colab.research.google.com/github/MEE-DRED/Data-Analyst/blob/main/Mildred_Ewenrim_Ebomah_WTF_2025_7575.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
MILDRED WERNRIM EBOMAH, WTF/2025/7575, mildredebomah@outlook.com


In [ ]:
NumPy Methods (1-40)

In [1]:
import numpy as np
# Create a 1D array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [2]:
import numpy as np
# Create array from 0 to 9
arr = np.arange(10)
print(arr)  # Output: [0 1 2 3 4 5 6 7 8 9]

[0 1 2 3 4 5 6 7 8 9]


In [3]:
import numpy as np
# Create 5 evenly spaced values between 0 and 10
arr = np.linspace(0, 10, 5)
print(arr)  # Output: [ 0.   2.5  5.   7.5 10. ]

[ 0.   2.5  5.   7.5 10. ]


In [4]:
import numpy as np
# Create a 3x3 array of zeros
arr = np.zeros((3, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
import numpy as np
# Create a 2x4 array of ones
arr = np.ones((2, 4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
import numpy as np
# Create a 4x4 identity matrix
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
import numpy as np
# Generate a 2x3 array of random numbers
arr = np.random.rand(2, 3)
print(arr)

[[0.21294556 0.19174578 0.13221903]
 [0.09183082 0.12501276 0.30133752]]


In [8]:
import numpy as np
# Generate 5 random numbers from normal distribution
arr = np.random.randn(5)
print(arr)

[ 0.30315532 -0.11018365  1.38819263  1.63070847 -0.56141045]


In [9]:
import numpy as np
# Generate 10 random integers between 1 and 100
arr = np.random.randint(1, 101, 10)
print(arr)

[21 94 41 94 63 54 37 48 56 70]


In [10]:
import numpy as np
# Reshape a 1D array into a 3x3 array
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
import numpy as np
# Create and transpose a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed = np.transpose(arr)
print(transposed)  # Shape becomes 3x2

[[1 4]
 [2 5]
 [3 6]]


In [12]:
import numpy as np
# Concatenate two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.concatenate([arr1, arr2])
print(result)  # Output: [1 2 3 4 5 6]

[1 2 3 4 5 6]


In [13]:
import numpy as np
# Stack arrays vertically
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack([arr1, arr2])
print(result)

[[1 2 3]
 [4 5 6]]


In [14]:
import numpy as np
# Stack arrays horizontally
arr1 = np.array([[1], [2]])
arr2 = np.array([[3], [4]])
result = np.hstack([arr1, arr2])
print(result)  # Output: [[1 3] [2 4]]

[[1 3]
 [2 4]]


In [15]:
import numpy as np
# Split array into 3 equal parts
arr = np.arange(9)
result = np.split(arr, 3)
print(result)  # Three arrays: [0,1,2], [3,4,5], [6,7,8]

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [16]:
import numpy as np
# Calculate mean of array
arr = np.array([10, 20, 30, 40, 50])
mean_value = np.mean(arr)
print(mean_value)  # Output: 30.0

30.0


In [17]:
import numpy as np
# Calculate median
arr = np.array([1, 3, 5, 7, 9])
median_value = np.median(arr)
print(median_value)  # Output: 5.0

5.0


In [18]:
import numpy as np
# Calculate standard deviation
arr = np.array([2, 4, 6, 8, 10])
std_value = np.std(arr)
print(std_value)

2.8284271247461903


In [19]:
import numpy as np
# Calculate variance
arr = np.array([1, 2, 3, 4, 5])
variance = np.var(arr)
print(variance)  # Output: 2.0

2.0


In [20]:
import numpy as np
# Calculate sum of all elements
arr = np.array([[1, 2], [3, 4]])
total = np.sum(arr)
print(total)  # Output: 10

10


In [21]:
import numpy as np
# Find minimum value
arr = np.array([15, 3, 28, 7, 12])
min_value = np.min(arr)
print(min_value)  # Output: 3

3


In [22]:
import numpy as np
# Find maximum value
arr = np.array([15, 3, 28, 7, 12])
max_value = np.max(arr)
print(max_value)  # Output: 28

28


In [23]:
import numpy as np
# Find index of minimum value
arr = np.array([15, 3, 28, 7, 12])
min_index = np.argmin(arr)
print(min_index)  # Output: 1

1


In [24]:
import numpy as np
# Find index of maximum value
arr = np.array([15, 3, 28, 7, 12])
max_index = np.argmax(arr)
print(max_index)  # Output: 2

2


In [25]:
import numpy as np
# Sort array in ascending order
arr = np.array([64, 25, 12, 22, 11])
sorted_arr = np.sort(arr)
print(sorted_arr)  # Output: [11 12 22 25 64]

[11 12 22 25 64]


In [26]:
import numpy as np
# Get indices that would sort the array
arr = np.array([64, 25, 12, 22, 11])
indices = np.argsort(arr)
print(indices)  # Output: [4 2 3 1 0]

[4 2 3 1 0]


In [40]:
import numpy as np
# Get unique values from array
arr = np.array([1, 2, 2, 3, 3, 3, 4])
unique_values = np.unique(arr)
print(unique_values)  # Output: [1 2 3 4]

[1 2 3 4]


In [27]:
import numpy as np
# Find indices where values are greater than 5
arr = np.array([2, 7, 4, 9, 1, 6])
indices = np.where(arr > 5)
print(indices)  # Output: (array([1, 3, 5]),)

(array([1, 3, 5]),)


In [28]:
import numpy as np
# Calculate dot product of two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print(dot_product)  # Output: 32 (1*4 + 2*5 + 3*6)

32


In [29]:
import numpy as np
# Matrix multiplication
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
result = np.matmul(arr1, arr2)
print(result)

[[19 22]
 [43 50]]


In [30]:
import numpy as np
# Raise each element to power of 2
arr = np.array([1, 2, 3, 4, 5])
result = np.power(arr, 2)
print(result)  # Output: [ 1  4  9 16 25]

[ 1  4  9 16 25]


In [31]:
import numpy as np
# Calculate square root of each element
arr = np.array([1, 4, 9, 16, 25])
result = np.sqrt(arr)
print(result)  # Output: [1. 2. 3. 4. 5.]

[1. 2. 3. 4. 5.]


In [32]:
import numpy as np
# Calculate exponential of each element
arr = np.array([1, 2, 3])
result = np.exp(arr)
print(result)  # Output: [ 2.71828183  7.3890561  20.08553692]

[ 2.71828183  7.3890561  20.08553692]


In [33]:
import numpy as np
# Calculate natural logarithm
arr = np.array([1, 2.71828183, 7.3890561])
result = np.log(arr)
print(result)  # Output: [0. 1. 2.]

[0. 1. 2.]


In [34]:
import numpy as np
# Get absolute values
arr = np.array([-5, -3, 0, 3, 5])
result = np.abs(arr)
print(result)  # Output: [5 3 0 3 5]

[5 3 0 3 5]


In [35]:
import numpy as np
# Round to 2 decimal places
arr = np.array([1.23456, 2.78901, 3.14159])
result = np.round(arr, 2)
print(result)  # Output: [1.23 2.79 3.14]

[1.23 2.79 3.14]


In [36]:
import numpy as np
# Apply floor function
arr = np.array([1.7, 2.3, -0.5, -1.9])
result = np.floor(arr)
print(result)  # Output: [ 1.  2. -1. -2.]

[ 1.  2. -1. -2.]


In [37]:
import numpy as np
# Apply ceiling function
arr = np.array([1.2, 2.7, -0.5, -1.1])
result = np.ceil(arr)
print(result)  # Output: [ 2.  3. -0. -1.]

[ 2.  3. -0. -1.]


In [38]:
import numpy as np
# Clip values between 2 and 8
arr = np.array([1, 3, 5, 7, 9, 11])
result = np.clip(arr, 2, 8)
print(result)  # Output: [2 3 5 7 8 8]

[2 3 5 7 8 8]


In [39]:
import numpy as np
# Calculate correlation between two variables
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])
correlation = np.corrcoef(x, y)
print(correlation)  # Perfect positive correlation: 1.0

[[1. 1.]
 [1. 1.]]


In [ ]:
Pandas Methods (1-40)

In [41]:
import pandas as pd
# Create DataFrame from dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


In [42]:
import pandas as pd
# Create a Series
ages = pd.Series([25, 30, 35], index=['Alice', 'Bob', 'Charlie'])
print(ages)

Alice      25
Bob        30
Charlie    35
dtype: int64


In [43]:
import pandas as pd
# Read CSV file (example with sample data)
# df = pd.read_csv('data.csv')
# For demonstration, create sample DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df)

   A  B
0  1  4
1  2  5
2  3  6


In [44]:
import pandas as pd
# View first 3 rows
df = pd.DataFrame({'A': range(10), 'B': range(10, 20)})
print(df.head(3))

   A   B
0  0  10
1  1  11
2  2  12


In [45]:
import pandas as pd
# View last 3 rows
df = pd.DataFrame({'A': range(10), 'B': range(10, 20)})
print(df.tail(3))

   A   B
7  7  17
8  8  18
9  9  19


In [46]:
import pandas as pd
# Get DataFrame information
df = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    2 non-null      object
 1   Age     2 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes


In [47]:
import pandas as pd
# Get statistical summary
df = pd.DataFrame({'Score': [85, 90, 78, 92, 88]})
print(df.describe())

           Score
count   5.000000
mean   86.600000
std     5.458938
min    78.000000
25%    85.000000
50%    88.000000
75%    90.000000
max    92.000000


In [48]:
import pandas as pd
# Get DataFrame dimensions
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print(df.shape)  # Output: (3, 2)

(3, 2)


In [49]:
import pandas as pd
# Get column names
df = pd.DataFrame({'Name': ['Alice'], 'Age': [25], 'City': ['NYC']})
print(df.columns)  # Output: Index(['Name', 'Age', 'City'], dtype='object')

Index(['Name', 'Age', 'City'], dtype='object')


In [50]:
import pandas as pd
# Get index labels
df = pd.DataFrame({'A': [1, 2, 3]}, index=['row1', 'row2', 'row3'])
print(df.index)  # Output: Index(['row1', 'row2', 'row3'], dtype='object')

Index(['row1', 'row2', 'row3'], dtype='object')


In [51]:
import pandas as pd
# Check data types
df = pd.DataFrame({'Name': ['Alice'], 'Age': [25], 'Score': [85.5]})
print(df.dtypes)

Name      object
Age        int64
Score    float64
dtype: object


In [52]:
import pandas as pd
import numpy as np
# Check for null values
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, np.nan]})
print(df.isnull())

       A      B
0  False  False
1   True  False
2  False   True


In [53]:
import pandas as pd
import numpy as np
# Check for NA values
df = pd.DataFrame({'A': [1, np.nan, 3]})
print(df.isna())

       A
0  False
1   True
2  False


In [54]:
import pandas as pd
import numpy as np
# Check for non-null values
df = pd.DataFrame({'A': [1, np.nan, 3]})
print(df.notna())

       A
0   True
1  False
2   True


In [55]:
import pandas as pd
import numpy as np
# Drop rows with any missing values
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [4, 5, 6]})
cleaned_df = df.dropna()
print(cleaned_df)

     A  B
0  1.0  4
2  3.0  6


In [56]:
import pandas as pd
import numpy as np
# Fill missing values with 0
df = pd.DataFrame({'A': [1, np.nan, 3], 'B': [np.nan, 5, 6]})
filled_df = df.fillna(0)
print(filled_df)

     A    B
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0


In [57]:
import pandas as pd
# Drop a column
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4], 'C': [5, 6]})
df_dropped = df.drop('C', axis=1)
print(df_dropped)

   A  B
0  1  3
1  2  4


In [58]:
import pandas as pd
# Rename columns
df = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df_renamed = df.rename(columns={'A': 'Column1', 'B': 'Column2'})
print(df_renamed)

   Column1  Column2
0        1        3
1        2        4


In [59]:
import pandas as pd
# Sort by Age column
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [30, 25, 35]})
sorted_df = df.sort_values('Age')
print(sorted_df)

      Name  Age
1      Bob   25
0    Alice   30
2  Charlie   35


In [60]:
import pandas as pd
# Sort by index
df = pd.DataFrame({'A': [1, 2, 3]}, index=[3, 1, 2])
sorted_df = df.sort_index()
print(sorted_df)

   A
1  2
2  3
3  1


In [61]:
import pandas as pd
# Group by category and calculate mean
df = pd.DataFrame({'Category': ['A', 'B', 'A', 'B'], 'Value': [10, 20, 30, 40]})
grouped = df.groupby('Category').mean()
print(grouped)

          Value
Category       
A          20.0
B          30.0


In [62]:
import pandas as pd
# Merge two DataFrames
df1 = pd.DataFrame({'ID': [1, 2], 'Name': ['Alice', 'Bob']})
df2 = pd.DataFrame({'ID': [1, 2], 'Score': [85, 90]})
merged = pd.merge(df1, df2, on='ID')
print(merged)

   ID   Name  Score
0   1  Alice     85
1   2    Bob     90


In [63]:
import pandas as pd
# Concatenate DataFrames vertically
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'A': [3, 4]})
result = pd.concat([df1, df2], ignore_index=True)
print(result)

   A
0  1
1  2
2  3
3  4


In [64]:
import pandas as pd
# Join DataFrames on index
df1 = pd.DataFrame({'A': [1, 2]}, index=['X', 'Y'])
df2 = pd.DataFrame({'B': [3, 4]}, index=['X', 'Y'])
joined = df1.join(df2)
print(joined)

   A  B
X  1  3
Y  2  4


In [65]:
import pandas as pd
# Create pivot table
df = pd.DataFrame({'Category': ['A', 'B', 'A'], 'Value': [10, 20, 30]})
pivot = df.pivot_table(values='Value', index='Category', aggfunc='sum')
print(pivot)

          Value
Category       
A            40
B            20


In [66]:
import pandas as pd
# Apply function to each column
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
result = df.apply(lambda x: x * 2)
print(result)

   A   B
0  2   8
1  4  10
2  6  12


In [67]:
import pandas as pd
# Map values in a Series
s = pd.Series([1, 2, 3, 4, 5])
mapped = s.map(lambda x: x ** 2)
print(mapped)  # Output: 1, 4, 9, 16, 25

0     1
1     4
2     9
3    16
4    25
dtype: int64


In [68]:
import pandas as pd
# Replace specific values
df = pd.DataFrame({'A': [1, 2, 3, 2, 1]})
replaced = df.replace(2, 999)
print(replaced)

     A
0    1
1  999
2    3
3  999
4    1


In [69]:
import pandas as pd
# Convert data type
df = pd.DataFrame({'A': ['1', '2', '3']})
df['A'] = df['A'].astype(int)
print(df.dtypes)

A    int64
dtype: object


In [70]:
import pandas as pd
# Count unique values
s = pd.Series(['A', 'B', 'A', 'C', 'B', 'A'])
counts = s.value_counts()
print(counts)  # A: 3, B: 2, C: 1

A    3
B    2
C    1
Name: count, dtype: int64


In [71]:
import pandas as pd
# Get unique values
s = pd.Series([1, 2, 2, 3, 3, 3, 4])
unique_vals = s.unique()
print(unique_vals)  # Output: [1 2 3 4]

[1 2 3 4]


In [72]:
import pandas as pd
# Count unique values per column
df = pd.DataFrame({'A': [1, 2, 2, 3], 'B': ['X', 'Y', 'X', 'Z']})
print(df.nunique())  # A: 3, B: 3

A    3
B    3
dtype: int64


In [73]:
import pandas as pd
# Find duplicate rows
df = pd.DataFrame({'A': [1, 2, 2, 3], 'B': [4, 5, 5, 6]})
duplicates = df.duplicated()
print(duplicates)

0    False
1    False
2     True
3    False
dtype: bool


In [74]:
import pandas as pd
# Remove duplicate rows
df = pd.DataFrame({'A': [1, 2, 2, 3], 'B': [4, 5, 5, 6]})
unique_df = df.drop_duplicates()
print(unique_df)

   A  B
0  1  4
1  2  5
3  3  6


In [75]:
import pandas as pd
# Set column as index
df = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
indexed_df = df.set_index('Name')
print(indexed_df)

       Age
Name      
Alice   25
Bob     30


In [76]:
import pandas as pd
# Reset index to default
df = pd.DataFrame({'A': [1, 2]}, index=['X', 'Y'])
reset_df = df.reset_index()
print(reset_df)

  index  A
0     X  1
1     Y  2


In [77]:
import pandas as pd
# Access row by label
df = pd.DataFrame({'A': [1, 2, 3]}, index=['X', 'Y', 'Z'])
row = df.loc['Y']
print(row)  # Output: A    2

A    2
Name: Y, dtype: int64


In [78]:
import pandas as pd
# Access row by position
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
row = df.iloc[1]  # Second row
print(row)  # Output: A    2, B    5

A    2
B    5
Name: 1, dtype: int64


In [79]:
import pandas as pd
# Filter using query
df = pd.DataFrame({'Age': [25, 30, 35], 'Score': [85, 90, 78]})
filtered = df.query('Age > 25 and Score >= 80')
print(filtered)

   Age  Score
1   30     90


In [80]:
import pandas as pd
# Save DataFrame to CSV
df = pd.DataFrame({'Name': ['Alice', 'Bob'], 'Age': [25, 30]})
# df.to_csv('output.csv', index=False)
print("DataFrame saved to CSV (example)")

DataFrame saved to CSV (example)
